language: python
python:
  - "3.5"
install:
  # Build/test dependencies
 - pip install -r requirements.txt -r requirements-dev.txt
script:
  - python setup.py code_quality
  #- python setup.py test
  - python setup.py install
